In [21]:
import pandas as pd

In [22]:
bookings = pd.read_csv('/content/bookings.csv', sep=';')
bookings_head = bookings.head(7)

In [23]:
bookings.shape

(119390, 21)

In [24]:
bookings.dtypes

Hotel                         object
Is Canceled                    int64
Lead Time                      int64
arrival full date             object
Arrival Date Year              int64
Arrival Date Month            object
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                          object
Country                       object
Reserved Room Type            object
Assigned room type            object
customer type                 object
Reservation Status            object
Reservation status_date       object
dtype: object

In [25]:
bookings.dtypes.value_counts()

object     10
int64      10
float64     1
dtype: int64

In [26]:
bookings

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [30]:
bookings.columns = bookings.columns.str.replace(' ', '_').str.lower() # Replacing spaces in column names with underscores and convert all characters to lowercase
bookings.head()

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03

In [39]:
top_countries = bookings.query('is_canceled == 0') \
                       .groupby('country') \
                       .size() \
                       .sort_values(ascending=False) \
                       .head(5)
top_countries

country
PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
dtype: int64

In [41]:
bookings.groupby('hotel').stays_total_nights.mean().round(2) # Calculating the mean number of total nights stayed for each type of hotel

hotel
City Hotel      2.98
Resort Hotel    4.32
Name: stays_total_nights, dtype: float64

In [47]:
count_different_rooms = bookings[bookings['assigned_room_type'] != bookings['reserved_room_type']].shape[0] # Count the number of observations where the assigned room type differs from the reserved room type

print("Number of observations where the assigned room type differs from the reserved room type:", count_different_rooms)

Number of observations where the assigned room type differs from the reserved room type: 14917

In [59]:
# Grouping data by arrival year and month, counting the number of bookings in each month
monthly_bookings_2016 = bookings[bookings['arrival_date_year'] == 2016].groupby('arrival_date_month').size()

# Finding the most popular month in 2016
most_popular_month_2016 = monthly_bookings_2016.idxmax()

print("Most popular month for bookings in 2016:", most_popular_month_2016)

# Repeat for 2017
monthly_bookings_2017 = bookings[bookings['arrival_date_year'] == 2017].groupby('arrival_date_month').size()
most_popular_month_2017 = monthly_bookings_2017.idxmax()

print("Most popular month for bookings in 2017:", most_popular_month_2017)

Most popular month for bookings in 2016: October
Most popular month for bookings in 2017: May

In [67]:
bookings.groupby(['arrival_date_year','arrival_date_month'], as_index=False).aggregate({'is_canceled' : 'sum'}) # Group the data by arrival year and month, calculating the sum of canceled bookings for each month
# or bookings.groupby(['arrival_date_year','arrival_date_month']).is_canceled.sum()

    arrival_date_year arrival_date_month  is_canceled
0                2015             August         1598
1                2015           December          973
2                2015               July         1259
3                2015           November          486
4                2015            October         1732
5                2015          September         2094
6                2016              April         2061
7                2016             August         1825
8                2016           December         1398
9                2016           February         1337
10               2016            January          557
11               2016               July         1499
12               2016               June         2096
13               2016              March         1477
14               2016                May         1915
15               2016           November         1636
16               2016            October         2514
17               2016          September         2022
18               2017              April         2463
19               2017             August         1816
20               2017           February         1359
21               2017            January         1250
22               2017               July         1984
23               2017               June         2439
24               2017              March         1672
25               2017                May         2762

In [73]:
bookings[['adults', 'children', 'babies']].mean()

adults      1.856403
children    0.103890
babies      0.007949
dtype: float64

In [77]:
bookings['total_kids'] = bookings.children + bookings.babies
bookings.groupby('hotel').total_kids.mean().round(2)

hotel
City Hotel      0.10
Resort Hotel    0.14
Name: total_kids, dtype: float64

In [79]:
# Creating the variable has_kids
bookings['has_kids'] = (bookings['children'] + bookings['babies'] > 0)

# Calculating the churn rate for the group with kids
churn_rate_with_kids = (bookings[bookings['has_kids']]['is_canceled'].mean()) * 100

# Calculating the churn rate for the group without kids
churn_rate_without_kids = (bookings[~bookings['has_kids']]['is_canceled'].mean()) * 100

# Determining the highest churn rate
max_churn_rate = max(churn_rate_with_kids, churn_rate_without_kids)

print(round(max_churn_rate, 2))

37.22